# Generated by Django 6.0.3 on 2026-03-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_seed_sepa_countries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset (Money you have)'), ('LIABILITY', 'Liability (Money you owe)'), ('REVENUE', 'Revenue (Income)'), ('EXPENSE', 'Expense (Costs)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ledger.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bic', models.CharField(max_length=11, unique=True, verbose_name='BIC/SWIFT')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutes', to='common.country')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger.account')),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.financialinstitute')),
            ],
            bases=('ledger.account',),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ledger.account')),
                ('last_four', models.CharField(max_length=4)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.financialinstitute')),
            ],
            bases=('ledger.account',),
        ),
    ]
