# Generated by Django 6.0.3 on 2026-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2 (e.g., DE)', max_length=2, unique=True)),
                ('iso_code_3', models.CharField(help_text='ISO 3166-1 alpha-3 (e.g., DEU)', max_length=3, unique=True)),
                ('is_eu_member', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
